using Domain.Entities;

namespace Infrastructure.Persistence.DataSeed;

public static class SeedBreeds
{
    public static List<Breed> Seed()
    {
        return
        [
            // Dogs
            new Breed() { Id = 1, Name = "Affenpinscher", SpeciesId = 1 },
            new Breed() { Id = 2, Name = "Galgo Afegão", SpeciesId = 1 },
            new Breed() { Id = 3, Name = "Airedale Terrier", SpeciesId = 1 },
            new Breed() { Id = 4, Name = "Akita", SpeciesId = 1 },
            new Breed() { Id = 5, Name = "Malamute do Alasca", SpeciesId = 1 },
            new Breed() { Id = 6, Name = "Bulldog Americano", SpeciesId = 1 },
            new Breed() { Id = 7, Name = "Pit Bull Terrier Americano", SpeciesId = 1 },
            new Breed() { Id = 8, Name = "Staffordshire Terrier Americano", SpeciesId = 1 },
            new Breed() { Id = 9, Name = "Boiadeiro Australiano", SpeciesId = 1 },
            new Breed() { Id = 10, Name = "Pastor Australiano", SpeciesId = 1 },
            new Breed() { Id = 11, Name = "Terrier Australiano", SpeciesId = 1 },
            new Breed() { Id = 12, Name = "Basenji", SpeciesId = 1 },
            new Breed() { Id = 13, Name = "Basset Hound", SpeciesId = 1 },
            new Breed() { Id = 14, Name = "Beagle", SpeciesId = 1 },
            new Breed() { Id = 15, Name = "Bearded Collie", SpeciesId = 1 },
            new Breed() { Id = 16, Name = "Bedlington Terrier", SpeciesId = 1 },
            new Breed() { Id = 17, Name = "Boiadeiro Bernês", SpeciesId = 1 },
            new Breed() { Id = 18, Name = "Bichon Frisé", SpeciesId = 1 },
            new Breed() { Id = 19, Name = "Bloodhound", SpeciesId = 1 },
            new Breed() { Id = 20, Name = "Border Collie", SpeciesId = 1 },
            new Breed() { Id = 21, Name = "Border Terrier", SpeciesId = 1 },
            new Breed() { Id = 22, Name = "Borzoi", SpeciesId = 1 },
            new Breed() { Id = 23, Name = "Boston Terrier", SpeciesId = 1 },
            new Breed() { Id = 24, Name = "Boxer", SpeciesId = 1 },
            new Breed() { Id = 25, Name = "Spaniel Boykin", SpeciesId = 1 },
            new Breed() { Id = 26, Name = "Briard", SpeciesId = 1 },
            new Breed() { Id = 27, Name = "Bretão", SpeciesId = 1 },
            new Breed() { Id = 28, Name = "Griffon de Bruxelas", SpeciesId = 1 },
            new Breed() { Id = 29, Name = "Bull Terrier", SpeciesId = 1 },
            new Breed() { Id = 30, Name = "Bulldog", SpeciesId = 1 },
            new Breed() { Id = 31, Name = "Bullmastiff", SpeciesId = 1 },
            new Breed() { Id = 32, Name = "Cairn Terrier", SpeciesId = 1 },
            new Breed() { Id = 33, Name = "Cane Corso", SpeciesId = 1 },
            new Breed() { Id = 34, Name = "Cavalier King Charles Spaniel", SpeciesId = 1 },
            new Breed() { Id = 35, Name = "Retriever de Chesapeake Bay", SpeciesId = 1 },
            new Breed() { Id = 36, Name = "Chihuahua", SpeciesId = 1 },
            new Breed() { Id = 37, Name = "Cão de Crista Chinês", SpeciesId = 1 },
            new Breed() { Id = 38, Name = "Chow Chow", SpeciesId = 1 },
            new Breed() { Id = 39, Name = "Clumber Spaniel", SpeciesId = 1 },
            new Breed() { Id = 40, Name = "Cocker Spaniel", SpeciesId = 1 },
            new Breed() { Id = 41, Name = "Collie", SpeciesId = 1 },
            new Breed() { Id = 42, Name = "Coonhound", SpeciesId = 1 },
            new Breed() { Id = 43, Name = "Corgi", SpeciesId = 1 },
            new Breed() { Id = 44, Name = "Coton de Tulear", SpeciesId = 1 },
            new Breed() { Id = 45, Name = "Dachshund", SpeciesId = 1 },
            new Breed() { Id = 46, Name = "Dálmata", SpeciesId = 1 },
            new Breed() { Id = 47, Name = "Doberman Pinscher", SpeciesId = 1 },
            new Breed() { Id = 48, Name = "Dogo Argentino", SpeciesId = 1 },
            new Breed() { Id = 49, Name = "Dogue de Bordeaux", SpeciesId = 1 },
            new Breed() { Id = 50, Name = "Bulldog Inglês", SpeciesId = 1 },
            new Breed() { Id = 51, Name = "Setter Inglês", SpeciesId = 1 },
            new Breed() { Id = 52, Name = "Spaniel de Springer Inglês", SpeciesId = 1 },
            new Breed() { Id = 53, Name = "Retriever de Pelo Liso", SpeciesId = 1 },
            new Breed() { Id = 54, Name = "Bulldog Francês", SpeciesId = 1 },
            new Breed() { Id = 55, Name = "Pastor Alemão", SpeciesId = 1 },
            new Breed() { Id = 56, Name = "Pointer Alemão de Pelo Curto", SpeciesId = 1 },
            new Breed() { Id = 57, Name = "Golden Retriever", SpeciesId = 1 },
            new Breed() { Id = 58, Name = "Dog Alemão", SpeciesId = 1 },
            new Breed() { Id = 59, Name = "Cão da Serra da Estrela", SpeciesId = 1 },
            new Breed() { Id = 60, Name = "Galgo Inglês", SpeciesId = 1 },
            new Breed() { Id = 61, Name = "Havanês", SpeciesId = 1 },
            new Breed() { Id = 62, Name = "Setter Irlandês", SpeciesId = 1 },
            new Breed() { Id = 63, Name = "Lobero Irlandês", SpeciesId = 1 },
            new Breed() { Id = 64, Name = "Jack Russell Terrier", SpeciesId = 1 },
            new Breed() { Id = 65, Name = "Chin Japonês", SpeciesId = 1 },
            new Breed() { Id = 66, Name = "Keeshond", SpeciesId = 1 },
            new Breed() { Id = 67, Name = "Labrador Retriever", SpeciesId = 1 },
            new Breed() { Id = 68, Name = "Lhasa Apso", SpeciesId = 1 },
            new Breed() { Id = 69, Name = "Maltês", SpeciesId = 1 },
            new Breed() { Id = 70, Name = "Mastim", SpeciesId = 1 },
            new Breed() { Id = 71, Name = "Pinscher Miniatura", SpeciesId = 1 },
            new Breed() { Id = 72, Name = "Terra Nova", SpeciesId = 1 },
            new Breed() { Id = 73, Name = "Elkhound Norueguês", SpeciesId = 1 },
            new Breed() { Id = 74, Name = "Papillon", SpeciesId = 1 },
            new Breed() { Id = 75, Name = "Pequinês", SpeciesId = 1 },
            new Breed() { Id = 76, Name = "Pembroke Welsh Corgi", SpeciesId = 1 },
            new Breed() { Id = 77, Name = "Spitz Alemão", SpeciesId = 1 },
            new Breed() { Id = 78, Name = "Poodle", SpeciesId = 1 },
            new Breed() { Id = 79, Name = "Cão de Água Português", SpeciesId = 1 },
            new Breed() { Id = 80, Name = "Pug", SpeciesId = 1 },
            new Breed() { Id = 81, Name = "Rottweiler", SpeciesId = 1 },
            new Breed() { Id = 82, Name = "São Bernardo", SpeciesId = 1 },
            new Breed() { Id = 83, Name = "Samoyeda", SpeciesId = 1 },
            new Breed() { Id = 84, Name = "Schipperke", SpeciesId = 1 },
            new Breed() { Id = 85, Name = "Schnauzer", SpeciesId = 1 },
            new Breed() { Id = 86, Name = "Scottish Terrier", SpeciesId = 1 },
            new Breed() { Id = 87, Name = "Shiba Inu", SpeciesId = 1 },
            new Breed() { Id = 88, Name = "Shih Tzu", SpeciesId = 1 },
            new Breed() { Id = 89, Name = "Vira-lata/SRD", SpeciesId = 1 },
            new Breed() { Id = 90, Name = "Husky Siberiano", SpeciesId = 1 },
            new Breed() { Id = 91, Name = "Staffordshire Bull Terrier", SpeciesId = 1 },
            new Breed() { Id = 92, Name = "Vizsla", SpeciesId = 1 },
            new Breed() { Id = 93, Name = "Weimaraner", SpeciesId = 1 },
            new Breed() { Id = 94, Name = "West Highland White Terrier", SpeciesId = 1 },
            new Breed() { Id = 95, Name = "Whippet", SpeciesId = 1 },
            new Breed() { Id = 96, Name = "Yorkshire Terrier", SpeciesId = 1 },

            // Cats
            new Breed() { Id = 97, Name = "Abissínio", SpeciesId = 2 },
            new Breed() { Id = 98, Name = "American Curl", SpeciesId = 2 },
            new Breed() { Id = 99, Name = "American Shorthair", SpeciesId = 2 },
            new Breed() { Id = 100, Name = "American Wirehair", SpeciesId = 2 },
            new Breed() { Id = 101, Name = "Angorá", SpeciesId = 2 },
            new Breed() { Id = 102, Name = "Balinês", SpeciesId = 2 },
            new Breed() { Id = 103, Name = "Bengal", SpeciesId = 2 },
            new Breed() { Id = 104, Name = "Birmanês", SpeciesId = 2 },
            new Breed() { Id = 105, Name = "Bobtail Americano", SpeciesId = 2 },
            new Breed() { Id = 106, Name = "Bobtail Japonês", SpeciesId = 2 },
            new Breed() { Id = 107, Name = "Bombay", SpeciesId = 2 },
            new Breed() { Id = 108, Name = "British Shorthair", SpeciesId = 2 },
            new Breed() { Id = 109, Name = "Burmês", SpeciesId = 2 },
            new Breed() { Id = 110, Name = "Chartreux", SpeciesId = 2 },
            new Breed() { Id = 111, Name = "Cornish Rex", SpeciesId = 2 },
            new Breed() { Id = 112, Name = "Devon Rex", SpeciesId = 2 },
            new Breed() { Id = 113, Name = "Egípcio Mau", SpeciesId = 2 },
            new Breed() { Id = 114, Name = "Europeu", SpeciesId = 2 },
            new Breed() { Id = 115, Name = "Exótico", SpeciesId = 2 },
            new Breed() { Id = 116, Name = "Himalaio", SpeciesId = 2 },
            new Breed() { Id = 117, Name = "Javanês", SpeciesId = 2 },
            new Breed() { Id = 118, Name = "Korat", SpeciesId = 2 },
            new Breed() { Id = 119, Name = "LaPerm", SpeciesId = 2 },
            new Breed() { Id = 120, Name = "Maine Coon", SpeciesId = 2 },
            new Breed() { Id = 121, Name = "Manx", SpeciesId = 2 },
            new Breed() { Id = 122, Name = "Mau Árabe", SpeciesId = 2 },
            new Breed() { Id = 123, Name = "Munchkin", SpeciesId = 2 },
            new Breed() { Id = 124, Name = "Norueguês da Floresta", SpeciesId = 2 },
            new Breed() { Id = 125, Name = "Ocicat", SpeciesId = 2 },
            new Breed() { Id = 126, Name = "Oriental", SpeciesId = 2 },
            new Breed() { Id = 127, Name = "Persa", SpeciesId = 2 },
            new Breed() { Id = 128, Name = "Peterbald", SpeciesId = 2 },
            new Breed() { Id = 129, Name = "Pixie-bob", SpeciesId = 2 },
            new Breed() { Id = 130, Name = "Ragdoll", SpeciesId = 2 },
            new Breed() { Id = 131, Name = "Russian Blue", SpeciesId = 2 },
            new Breed() { Id = 132, Name = "Savannah", SpeciesId = 2 },
            new Breed() { Id = 133, Name = "Scottish Fold", SpeciesId = 2 },
            new Breed() { Id = 134, Name = "Selkirk Rex", SpeciesId = 2 },
            new Breed() { Id = 135, Name = "Siamês", SpeciesId = 2 },
            new Breed() { Id = 136, Name = "Siberiano", SpeciesId = 2 },
            new Breed() { Id = 137, Name = "Singapura", SpeciesId = 2 },
            new Breed() { Id = 138, Name = "Snowshoe", SpeciesId = 2 },
            new Breed() { Id = 139, Name = "Somali", SpeciesId = 2 },
            new Breed() { Id = 140, Name = "Sphynx", SpeciesId = 2 },
            new Breed() { Id = 141, Name = "Vira-lata/SRD", SpeciesId = 2 },
            new Breed() { Id = 142, Name = "Tonkineses", SpeciesId = 2 },
            new Breed() { Id = 143, Name = "Toyger", SpeciesId = 2 },
            new Breed() { Id = 144, Name = "Turco Van", SpeciesId = 2 }
        ];
    }
}